name: falack_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  audioplayers: ^6.1.0
  cached_network_image: 3.4.0
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_webrtc: ^0.10.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  latlong2: ^0.9.1
  palette_generator: ^0.3.3+4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  signalr_core: ^1.1.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
    - assets/sound/
  generate: true
 
